### ISSUE TITLE
If empty excerpt of page_for_posts, defaults to excerpt of latest post. Intended?

### ISSUE THREAD

**Issue by daankortenbach** [seothemes/genesis-starter-theme#12]
If the excerpt of the page_for_posts page is empty, the page will default to the excerpt of the latest blog post. Is this intended?

https://github.com/seothemes/genesis-starter/blob/f74dfc9b8c08f6bfd30a9666cbb1d31fd408792e/includes/header.php#L175

**Comment by seothemes** [comment]
No, this is not intentional. It has been fixed in newer themes but is yet to be updated in the starter theme.

I'll push this update soon unless you want to submit a PR. See fix below:

```php
} elseif ( is_home() ) {

	$id = get_option( 'page_for_posts' );

	if ( has_excerpt( $id ) ) {

		printf( '<p itemprop="description">%s</p>', do_shortcode( get_the_excerpt( $id ) ) );

	}

}
```

**Comment by daankortenbach** [comment]
ping

**Comment by seothemes** [comment]
Fixed in latest version/child theme library - https://github.com/seothemes/child-theme-library/blob/master/functions/hero.php#L187
