### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by bisonbrah** [seothemes/genesis-starter-theme#31]
Im getting the following message when attempting to instal via cmd - all required assets are there FYI

`composer create-project seothemes/genesis-starter-theme hhgr-athletic dev-master && cd "$(\ls -1dt ./*/ | head -n 1)" && npm install && gulp
Installing seothemes/genesis-starter-theme (dev-master 4423669a4c71950ae5bab568108598d94034189f)
  - Installing seothemes/genesis-starter-theme (dev-master master): Cloning master from cache
Created project in hhgr-athletic
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package d2/core-asset-loader could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package d2/core-constants could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package d2/core-custom-colors could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package d2/core-genesis-layouts could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package d2/core-genesis-settings could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package d2/core-google-fonts could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package d2/core-hooks could not be found in any version, there may be a typo in the package name.
  Problem 8
    - The requested package d2/core-image-sizes could not be found in any version, there may be a typo in the package name.
  Problem 9
    - The requested package d2/core-plugin-activation could not be found in any version, there may be a typo in the package name.
  Problem 10
    - The requested package d2/core-simple-social-icons could not be found in any version, there may be a typo in the package name.
  Problem 11
    - The requested package d2/core-textdomain could not be found in any version, there may be a typo in the package name.
  Problem 12
    - The requested package d2/core-theme-support could not be found in any version, there may be a typo in the package name.
  Problem 13
    - The requested package d2/core-widget-areas could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

**Comment by seothemes** [comment]
It looks like the package hasn’t been automatically updated. For now just clone the repo instead of using `composer create-project`

**Comment by bisonbrah** [comment]
Right on - thanks man, I guess keep this open until this is corrected?

**Comment by seothemes** [comment]
Yep, we’ll keep this one open until it’s fixed.

**Comment by bisonbrah** [comment]
Any update on this?

**Comment by bisonbrah** [comment]
Any update on this?

**Comment by seothemes** [comment]
@bisonbrah I’ve been working on a major update which removes the non-dev composer packages so this issue will be resolved when I push those changes

**Comment by seothemes** [comment]
This should be fixed now.

**Comment by seothemes** [comment]
@bisonbrah want to test it out? Make sure you run `composer clear-cache` first.

**Comment by bisonbrah** [comment]
Seeing this now; but it appears theme install properly?!

`composer create-project seothemes/genesis-starter-theme airspace-custom dev-master && cd "$(\ls -1dt ./*/ | head -n 1)" && npm install && npm run build
Installing seothemes/genesis-starter-theme (dev-master 4967d6e230a784ab4e3cc83737de7cae7cd75721)
  - Installing seothemes/genesis-starter-theme (dev-master master): Cloning master from cache
Created project in airspace-custom
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package d2/core-asset-loader could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package d2/core-constants could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package d2/core-custom-colors could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package d2/core-genesis-layouts could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package d2/core-genesis-settings could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package d2/core-google-fonts could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package d2/core-hooks could not be found in any version, there may be a typo in the package name.
  Problem 8
    - The requested package d2/core-image-sizes could not be found in any version, there may be a typo in the package name.
  Problem 9
    - The requested package d2/core-plugin-activation could not be found in any version, there may be a typo in the package name.
  Problem 10
    - The requested package d2/core-simple-social-icons could not be found in any version, there may be a typo in the package name.
  Problem 11
    - The requested package d2/core-textdomain could not be found in any version, there may be a typo in the package name.
  Problem 12
    - The requested package d2/core-theme-support could not be found in any version, there may be a typo in the package name.
  Problem 13
    - The requested package d2/core-widget-areas could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

**Comment by seothemes** [comment]
Ok, did you run `composer clear-cache` first? The D2 packages are no longer dependencies so it shouldn't be trying to load them.

**Comment by nielszandberg** [comment]
Hi seothemes,

I got the same kind of messages when I tried to install via terminal.

Problem 1
    - The requested package seothemes/genesis-config-exporter could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by seothemes** [comment]
@nielszandberg fixed in 02e5b88. Try now with `composer require seothemes/genesis-starter-theme:dev-master`

**Comment by colinduwe** [comment]
Master composer.json still requires seothemes/genesis-config-exporter
3.5.1 does not.
What is genesis-config-exporter? Is it really required?

**Comment by seothemes** [comment]
@colinduwe genesis-config-exporter is only needed for commercial theme developers. It automatically generates the config files to be used by the Genesis Onboarding feature. https://github.com/seothemes/genesis-config-exporter

It's only a dev dependency, feel free to remove it from the composer.json file.
