### ISSUE TITLE
No sourcemaps or revisions

### ISSUE THREAD

**Issue by colinduwe** [seothemes/genesis-starter-theme#35]
Thanks for putting this out there. It's fantastic. I'm building my first project with it so please excuse a noob question but I'm not getting sourcemaps or revisions on my built assets. The project source has those tasks defined at the start of the mix file. I tried chaining them to the js and scss build tasks but that didn't seem to have any effect either. Any pointers would be greatly appreciated.

**Comment by seothemes** [comment]
Sourcemaps can be enabled by changing the devtool option in the webpack config, see https://webpack.js.org/configuration/devtool/

There was a reason why I switched them off by default but can't remember. Let me know if you run into any issues.
