### ISSUE TITLE
How to disable the 'Theme License' required section in theme

### ISSUE THREAD

**Issue by bisonbrah** [seothemes/genesis-starter-theme#36]
How do you remove the theme license require alert and custom field location? 

notice - https://d.pr/i/j4Pfbu
setting location - https://d.pr/i/R8ubtw

**Comment by seothemes** [comment]
Is that the latest version (3.5.3)?

**Comment by seothemes** [comment]
Closing as this issue has been fixed in the latest version but feel free to contact me for help removing the licensing stuff from older versions.
