### ISSUE TITLE
Script Issues

### ISSUE THREAD

**Issue by solepixel** [seothemes/genesis-starter-theme#9]
Couple of issues I found:

1. SCRIPT_DEBUG needs quotes when checking if defined. These lines:
```php
$suffix = defined( SCRIPT_DEBUG ) && SCRIPT_DEBUG ? '' : 'min.';
$folder = defined( SCRIPT_DEBUG ) && SCRIPT_DEBUG ? '' : 'min/';
```
Should read:
```php
$suffix = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : 'min.';
$folder = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : 'min/';
```
Ref: https://github.com/seothemes/genesis-starter/blob/master/functions.php#L202

2. My scripts.js file wasn't updating when I modified files inside of concat. I had to add this to `gulpfile.js` get scripts to re-compile:
```js
gulp.watch(paths.concat, ['scripts']);
```
Ref: https://github.com/seothemes/genesis-starter/blob/master/gulpfile.js#L483 (after)

**Comment by daankortenbach** [comment]
I can confirm.

**Comment by daankortenbach** [comment]
Fixed and merged, issue can be closed.
